README.md
lua/goto-preview.lua

This addresses users who want more control over the preview windows.
An example that addresses @serhez comment on issue #7.
```lua
post_open_hook = function(buffer, _)
vim.api.nvim_buf_set_keymap(buffer, 'n', 'q', ':q<CR>', {noremap = true})
end
```

Add new post_open_hook function.

---

lua/goto-preview.lua

The preview broke with the new LSP handler function format which was changed in this pr:
https://github.com/neovim/neovim/pull/15504
Closes #20.
This was done hopefully in a backwards compatible way so the plugin should still work even if one hasn't updated Neovim.

Adhere to new lsp handler format

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua
lua/telescope/_extensions/gotopreview.lua

Added support for LSP References preview calls.
One can now cycle between references through the use of [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)
Upon selection a preview window of the reference is triggered.
https://user-images.githubusercontent.com/2881382/133213596-b5795cd9-c84f-4561-bf66-49ea65b7c48b.mp4

Add support for references previews through telescope.nvim

---

lua/goto-preview.lua
lua/goto-preview/lib.lua

This fixes a problem I had with the close all windows function where the lib.windows variable was usually empty. Even if this problem doesn't affect everyone, I do think this implimentation is simpler and less likely to generate future bugs.

Refactor close_all_win()

---

lua/goto-preview.lua
lua/goto-preview/lib.lua

Revert to setting specific zindex but do not use the list of windows for the close all windows mechanism. Closes #34.

Revert to setting specific zindex

---

lua/goto-preview.lua
lua/goto-preview/lib.lua

The hook was not being called if one navigated into a definition that
the source was in a different file, hence triggering an opening of a new
buffer. That new buffer would not have the hook function called on it,
even if it was originally opened from a goto-preview window.
This commit:
- Changes how autocmd is setup. i.e setting it up only once now, not
once per call.
- Adds a BufEnter autocmd for goto-preview that checks if the opened
buffer's window is a goto-preview window, if it is, runs the hooks
just like it would previously for a goto-preview open floating window
call.
Closes #17.

Fix post_open_hook

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua

To make the public APIs open to future extension. See #44 and #46 for the discussion.

Make parameters to goto_preview_{definition/implementation} be a table

---

lua/goto-preview.lua

Neovim's builtin client actually adds the `context.includeDeclaration = true` in its call, I'm doing the raw call myself, bypassing what the builtin client does by default, hence the issue.
Ref:
https://github.com/neovim/neovim/blob/1f3c0593eb1d4e54ce1edf35da67d184807a9280/runtime/lua/vim/lsp/buf.lua#L314
Closes #50

Fix not passing a context on the references call

---

lua/goto-preview/lib.lua

Without this change, I get this warning: `locations_to_items must be called with valid offset encoding`
It's probably not safe to assume utf-8 all the time, so if you have a better way to derive the encoding, that should probably be used instead.

Fix warning with locations_to_items

---

README.md

Cleans up the documentation so copy and pasting the default configuration doesn't throw errors

docs: ensure default config works if copied

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua

Closes #81
This commit also stops using `vim.api.nvim_set_keymap` in favour of `vim.keymap.set` for setting mappings.

Isolate telescope delendency to the open_references_previewer call

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua

Usage:
```lua
require("goto-preview").close_all_win { skip_curr_window = true }
```
This option does as expected, skips the current window when closing all the preview windows.

Add `skip_curr_window` option to `close_all_win` function.

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua

Adds file path and title position to the floating window title if enabled
[README.md]
- Add options for stacking floating preview windows
- Add option for setting the preview window title as the filename [lua/goto-preview/lib.lua]
- Add the file path to the floating window title if enabled
- Add the title position to the floating window if enabled [lua/goto-preview.lua]
- Add a `preview_window_title` configuration option
- Reformat `get_config` function in `lsp_configs`
Closes #92

Add options for customizing preview window title and position.

---

lua/goto-preview/lib.lua

- Add `set_title` and `set_title_pos` functions to `lib.lua` for setting the title and position of a preview window respectively
- Refactor `M.open_floating_win` function in `lib.lua` to use the new `set_title` and `set_title_pos` functions

Make preview window title handling backwards compatible

---

lua/goto-preview/lib.lua

Hey I just discovered a case where the post_close_hook doesn't execute and it should. You can test this out by opening a floating window preview in the current buffer. For example you're in file.py and the definition that you want to go to is also in file.py the post close hook won't execute after closing the preview window. Sorry I missed this case in my previous pull request! This fixes it.
If there's any implementation changes you'd prefer or formatting please let me know!

fix: Add case where post_close_hook should run

---

lua/goto-preview.lua
lua/goto-preview/lib.lua

Implement the feature of jumping straight into reference if it's in the current file and refactored `open_floating_win` a bit.

Implement feature #59

---

lua/goto-preview/lib.lua

in my case the `vim.lsp.handlers` table does not contain the `textDocument/definition`. therefore I've implemented an approach that will iterate over `vim.lsp.handlers` to get the first `textDocument/*` handler instead of hardcoded handler.

fix get_config

---

README.md

Hi. Based on PR https://github.com/rmagatti/goto-preview/pull/110, we now have the `same_file_float_preview` option. I noticed there is no documentation for this option, especially in the README file, so with this PR i have added. You might also consider closing issue https://github.com/rmagatti/goto-preview/issues/59 by linking this PR or https://github.com/rmagatti/goto-preview/pull/110, cause i think it had solved. Thanks!

docs: added same_file_float_preview option

---

README.md
lua/goto-preview.lua
lua/goto-preview/lib.lua

Closes #127. This adds support for [fzf-lua](https://github.com/ibhagwan/fzf-lua), [snacks.picker](https://github.com/folke/snacks.nvim), [mini.pick](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-pick.md), or `vim.ui.select()` as a fallback. Unfortunately fzf-lua and snacks both call their own respective lsp-reference finder in this implementation, thus making unnecessary calls to the vim api. I did not find a trivial way to avoid this.

Add support for more picker providers

---

lua/goto-preview.lua

It should have been false by default to begin with; `true` likely slipped in during my testing
Addressed https://github.com/rmagatti/goto-preview/issues/135#issuecomment-2709222910

vim-ui-input should be opt-in

---

lua/goto-preview/health.lua

the has_logger  is harcoded to false, hence logger's health check never become true ;)

Fix(health): Remove hardcoded has_logger

---

lua/goto-preview.lua

- Dynamically registered capabilities are not available in client.server_capabilities.

fix: Use supports_method() to check providers

---

README.md
lua/goto-preview.lua

- Remove early return when no capable clients found for textDocument/definition
- Implement fallback strategy: prefer capable clients, but attempt request with all clients if none advertise capability
- Add deterministic client selection to handle multiple LSP scenarios gracefully
- Update documentation to explain capability detection approach
- Fixes compatibility with language servers like jdtls that support definitions but don't advertise definitionProvider
Fixes #145

Fix overly strict definitionProvider capability check
