rmagatti/goto-preview

- README.md
- lua/goto-preview.lua
> Do not depend on vimp and update readme with default mappings

- README.md
- lua/goto-preview.lua
> Improve readme, add opacity config, and handle lack of support for RFC file schema URI

- README.md
- lua/goto-preview.lua
Closes #12
Closes #10 
Closes #9
> Remove vimpeccable notice and a few other misc improvements

- lua/goto-preview.lua
> Fix nil lsp_configs issue when calling setup with empty object

- lua/goto-preview/lib.lua
> Mitigate compatibility issue with ZenMode. 

- lua/goto-preview.lua
- lua/goto-preview/lib.lua
- lua/telescope/_extensions/gotopreview.lua
> Make telescope optional

- .stylua.toml
- README.md
- lua/goto-preview.lua
- lua/goto-preview/lib.lua
- lua/telescope/_extensions/gotopreview.lua
> Add option to toggle auto focus on the preview window.

- .stylua.toml
- README.md
- lua/goto-preview.lua
- lua/goto-preview/lib.lua
> Add force_close option

- lua/goto-preview.lua
- lua/goto-preview/lib.lua
> fix: stop throwing error when response from the lsp is an empty table.

- lua/goto-preview.lua
So you can do `require('goto-preview').setup()`
> Accept `nil` config in `setup()`

- lua/goto-preview/lib.lua
solves https://github.com/rmagatti/goto-preview/issues/66
> Don't set parent buffer as hidden

- README.md
also add links to plugin managers
> add vim-plug installation instructions

- README.md
- lua/goto-preview.lua
https://user-images.githubusercontent.com/90083127/179449442-9184f244-fd17-486b-ac6f-cbf7808b1635.mov
> add type definition previewer

- lua/goto-preview.lua
This will get picked up by which-keys.
> add descriptions for default keymaps

- README.md
- lua/goto-preview.lua
- lua/goto-preview/lib.lua
This should close out the issue here:
https://github.com/rmagatti/goto-preview/issues/102
I was looking for something like this as well and had some free time today. If there are any formatting issues or if you'd prefer a different implementation let me know. I went with what seemed to be the simplest which was in essence mirroring the post_open_hook.
> feat: Add post_close_hook option

- README.md
- lua/goto-preview.lua
Hi, I added "textDocument/declaration" functionality, because it was missing. I hope you agree. Great plugin 👍
> added 'textDocument/declaration' functionality

- lua/goto-preview/lib.lua
> Focus previous preview window if there are multiple chained

- README.md
- lua/goto-preview.lua
- lua/goto-preview/lib.lua
Implements #118. While there are no tests, I tried it out for a day at work and it worked as intended.
> Add configurable starting zindex

- README.md
> Improve readme as per #88

- lua/goto-preview.lua
> Pass offset_encoding into make_position_params
